# Generated by Django 4.0.5 on 2022-06-02 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_profiles_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_name',
            new_name='username',
        ),
    ]
